include:
  - project: "nets-mitid-broker/pipelines.templates"
    ref: master
    file: "/templates.yml"
  - project: "nets-mitid-broker/pipelines.templates"
    ref: master
    file: "/deploytemplates.yml"


image: docker:19.03.11

stages:
  - build
  - publish
  - netstest
  - netspp
  - netsprod  

variables:
  VERSION: "0.3.0"  
  APPLICATION_NAME: integrationclient
  IMAGE_NAME: integrationclient
  INGRESS_SECRET_NAME: sg-tls-wildcard
  CURRENT_ENVIRONMENT: dev  

build:
  stage: build
  extends: .buildDockerImage
  variables:
    CONTEXT: "."

publish:
  stage: publish
  dependencies:
    - build
  extends: .publishToAcr

deploy-netstest:
  stage: netstest
  dependencies:
    - publish
  extends: .deployAks
  variables:
    NAMESPACE: netstest
    APPSETTINGS__AUTHORITY: 'https://test.netseidbroker.dk/op'
    APPSETTINGS__CLIENTID: '0ce039a9-ae70-4c5c-a225-c0d3dc2d2706'
    APPSETTINGS__CLIENTSECRET: 'Po05bJAuMC7wpDjyg/mvMbnxsaiDispz8TYg320oiTDp4rCcWQSXJI8QONle2K32HNCoUzF/D+AXAYwngzMF9Q=='
    HOSTNAME: 'brokerdemo-test.signaturgruppen.dk' 

deploy-netspp:
  only:
    - master
  when: manual
  stage: netspp
  environment: pp
  dependencies:
    - publish
  extends: .deployAks
  variables:
    NAMESPACE: netspp
    APPSETTINGS__AUTHORITY: 'https://pp.netseidbroker.dk/op'
    APPSETTINGS__CLIENTID: '14148e23-1d32-4d5b-a7ef-8935fdf65836'
    HOSTNAME: 'brokerdemo-pp.signaturgruppen.dk'        

deploy-netsprod:
  only:
    - master
  when: manual
  stage: netsprod
  environment: prod
  dependencies:
    - publish
  extends: .deployAks
  variables:
    NAMESPACE: netsprod
    APPSETTINGS__AUTHORITY: 'https://netseidbroker.dk/op/'
    APPSETTINGS__CLIENTID: '7997f267-6bb4-448d-b718-309a0ac20876'
    HOSTNAME: 'brokerdemo.signaturgruppen.dk'        